# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../qt/simplevizwidget.ui'
#
# Created: Thu Aug 13 15:52:11 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SimpleVizWidget(object):
    def setupUi(self, SimpleVizWidget):
        SimpleVizWidget.setObjectName("SimpleVizWidget")
        SimpleVizWidget.resize(580, 616)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SimpleVizWidget.sizePolicy().hasHeightForWidth())
        SimpleVizWidget.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtGui.QHBoxLayout(SimpleVizWidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dockWidget = QtGui.QDockWidget(SimpleVizWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(230, 178))
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 250, 552))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolBox = QtGui.QToolBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBox.setAccessibleName("")
        self.toolBox.setStyleSheet("QToolBox::tab {\n"
"         background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                     stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                     stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"         border-radius: 5px;\n"
"         color: black;\n"
"     }\n"
"\n"
"     QToolBox::tab:selected { /* italicize selected tabs */\n"
"         font: bold;\n"
"         color: black;\n"
"     }\n"
"QToolBox {\n"
"    padding : 0\n"
"}")
        self.toolBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox.setObjectName("toolBox")
        self.graphics = QtGui.QWidget()
        self.graphics.setGeometry(QtCore.QRect(0, 0, 250, 396))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphics.sizePolicy().hasHeightForWidth())
        self.graphics.setSizePolicy(sizePolicy)
        self.graphics.setObjectName("graphics")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.graphics)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.region_widget = QtGui.QWidget(self.graphics)
        self.region_widget.setObjectName("region_widget")
        self.formLayout_5 = QtGui.QFormLayout(self.region_widget)
        self.formLayout_5.setContentsMargins(3, 3, 3, 3)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setSpacing(3)
        self.formLayout_5.setObjectName("formLayout_5")
        self.region_label = QtGui.QLabel(self.region_widget)
        self.region_label.setObjectName("region_label")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.region_label)
        self.region_chooser = RegionChooserWidget(self.region_widget)
        self.region_chooser.setObjectName("region_chooser")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.region_chooser)
        self.verticalLayout_3.addWidget(self.region_widget)
        self.scene_editor = SceneEditorWidget(self.graphics)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scene_editor.sizePolicy().hasHeightForWidth())
        self.scene_editor.setSizePolicy(sizePolicy)
        self.scene_editor.setObjectName("scene_editor")
        self.verticalLayout_3.addWidget(self.scene_editor)
        self.toolBox.addItem(self.graphics, "")
        self.view = QtGui.QWidget()
        self.view.setGeometry(QtCore.QRect(0, 0, 250, 396))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view.sizePolicy().hasHeightForWidth())
        self.view.setSizePolicy(sizePolicy)
        self.view.setObjectName("view")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.view)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sceneviewer_editor_widget = SceneviewerEditorWidget(self.view)
        self.sceneviewer_editor_widget.setObjectName("sceneviewer_editor_widget")
        self.verticalLayout_5.addWidget(self.sceneviewer_editor_widget)
        self.toolBox.addItem(self.view, "")
        self.time = QtGui.QWidget()
        self.time.setGeometry(QtCore.QRect(0, 0, 250, 396))
        self.time.setObjectName("time")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.time)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.time_autorange_button = QtGui.QPushButton(self.time)
        self.time_autorange_button.setObjectName("time_autorange_button")
        self.verticalLayout_8.addWidget(self.time_autorange_button)
        self.frame_2 = QtGui.QFrame(self.time)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout_4 = QtGui.QFormLayout(self.frame_2)
        self.formLayout_4.setObjectName("formLayout_4")
        self.time_minimum_label = QtGui.QLabel(self.frame_2)
        self.time_minimum_label.setObjectName("time_minimum_label")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.time_minimum_label)
        self.time_minimum_lineedit = QtGui.QLineEdit(self.frame_2)
        self.time_minimum_lineedit.setObjectName("time_minimum_lineedit")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.time_minimum_lineedit)
        self.time_maximum_label = QtGui.QLabel(self.frame_2)
        self.time_maximum_label.setObjectName("time_maximum_label")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.time_maximum_label)
        self.time_maximum_lineedit = QtGui.QLineEdit(self.frame_2)
        self.time_maximum_lineedit.setObjectName("time_maximum_lineedit")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.time_maximum_lineedit)
        self.time_lineedit = QtGui.QLineEdit(self.frame_2)
        self.time_lineedit.setObjectName("time_lineedit")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.time_lineedit)
        self.time_label = QtGui.QLabel(self.frame_2)
        self.time_label.setObjectName("time_label")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.time_label)
        self.verticalLayout_8.addWidget(self.frame_2)
        self.time_slider = QtGui.QSlider(self.time)
        self.time_slider.setMaximum(10000)
        self.time_slider.setSingleStep(10)
        self.time_slider.setPageStep(100)
        self.time_slider.setOrientation(QtCore.Qt.Horizontal)
        self.time_slider.setObjectName("time_slider")
        self.verticalLayout_8.addWidget(self.time_slider)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.toolBox.addItem(self.time, "")
        self.rendering = QtGui.QWidget()
        self.rendering.setGeometry(QtCore.QRect(0, 0, 250, 396))
        self.rendering.setObjectName("rendering")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.rendering)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tessellation_groupbox = QtGui.QGroupBox(self.rendering)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tessellation_groupbox.sizePolicy().hasHeightForWidth())
        self.tessellation_groupbox.setSizePolicy(sizePolicy)
        self.tessellation_groupbox.setObjectName("tessellation_groupbox")
        self.formLayout_2 = QtGui.QFormLayout(self.tessellation_groupbox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.tessellation_minimum_divisions_label = QtGui.QLabel(self.tessellation_groupbox)
        self.tessellation_minimum_divisions_label.setObjectName("tessellation_minimum_divisions_label")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.tessellation_minimum_divisions_label)
        self.tessellation_minimum_divisions_lineedit = QtGui.QLineEdit(self.tessellation_groupbox)
        self.tessellation_minimum_divisions_lineedit.setObjectName("tessellation_minimum_divisions_lineedit")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.tessellation_minimum_divisions_lineedit)
        self.tessellation_refinement_factors_label = QtGui.QLabel(self.tessellation_groupbox)
        self.tessellation_refinement_factors_label.setObjectName("tessellation_refinement_factors_label")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.tessellation_refinement_factors_label)
        self.tessellation_refinement_factors_lineedit = QtGui.QLineEdit(self.tessellation_groupbox)
        self.tessellation_refinement_factors_lineedit.setObjectName("tessellation_refinement_factors_lineedit")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.tessellation_refinement_factors_lineedit)
        self.tessellation_circle_divisions_label = QtGui.QLabel(self.tessellation_groupbox)
        self.tessellation_circle_divisions_label.setObjectName("tessellation_circle_divisions_label")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.tessellation_circle_divisions_label)
        self.tessellation_circle_divisions_lineedit = QtGui.QLineEdit(self.tessellation_groupbox)
        self.tessellation_circle_divisions_lineedit.setObjectName("tessellation_circle_divisions_lineedit")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.tessellation_circle_divisions_lineedit)
        self.verticalLayout_7.addWidget(self.tessellation_groupbox)
        self.perturb_lines_checkbox = QtGui.QCheckBox(self.rendering)
        self.perturb_lines_checkbox.setObjectName("perturb_lines_checkbox")
        self.verticalLayout_7.addWidget(self.perturb_lines_checkbox)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.toolBox.addItem(self.rendering, "")
        self.data_colouring = QtGui.QWidget()
        self.data_colouring.setGeometry(QtCore.QRect(0, 0, 250, 396))
        self.data_colouring.setObjectName("data_colouring")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.data_colouring)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.spectrum_autorange_button = QtGui.QPushButton(self.data_colouring)
        self.spectrum_autorange_button.setObjectName("spectrum_autorange_button")
        self.verticalLayout_6.addWidget(self.spectrum_autorange_button)
        self.frame_3 = QtGui.QFrame(self.data_colouring)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout_3 = QtGui.QFormLayout(self.frame_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.spectrum_minimum_label = QtGui.QLabel(self.frame_3)
        self.spectrum_minimum_label.setObjectName("spectrum_minimum_label")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.spectrum_minimum_label)
        self.spectrum_minimum_lineedit = QtGui.QLineEdit(self.frame_3)
        self.spectrum_minimum_lineedit.setObjectName("spectrum_minimum_lineedit")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.spectrum_minimum_lineedit)
        self.spectrum_maximum_lineedit = QtGui.QLineEdit(self.frame_3)
        self.spectrum_maximum_lineedit.setObjectName("spectrum_maximum_lineedit")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.spectrum_maximum_lineedit)
        self.spectrum_maximum_label = QtGui.QLabel(self.frame_3)
        self.spectrum_maximum_label.setObjectName("spectrum_maximum_label")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.spectrum_maximum_label)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.spectrum_add_colour_bar_button = QtGui.QPushButton(self.data_colouring)
        self.spectrum_add_colour_bar_button.setObjectName("spectrum_add_colour_bar_button")
        self.verticalLayout_6.addWidget(self.spectrum_add_colour_bar_button)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.toolBox.addItem(self.data_colouring, "")
        self.output = QtGui.QWidget()
        self.output.setGeometry(QtCore.QRect(0, 0, 250, 396))
        self.output.setObjectName("output")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.output)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.save_image_button = QtGui.QPushButton(self.output)
        self.save_image_button.setObjectName("save_image_button")
        self.verticalLayout_9.addWidget(self.save_image_button)
        self.save_webgl_button = QtGui.QPushButton(self.output)
        self.save_webgl_button.setObjectName("save_webgl_button")
        self.verticalLayout_9.addWidget(self.save_webgl_button)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.toolBox.addItem(self.output, "")
        self.verticalLayout_2.addWidget(self.toolBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        self.frame = QtGui.QFrame(self.dockWidgetContents)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.view_all_button = QtGui.QPushButton(self.frame)
        self.view_all_button.setObjectName("view_all_button")
        self.horizontalLayout_2.addWidget(self.view_all_button)
        self.done_button = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.done_button.sizePolicy().hasHeightForWidth())
        self.done_button.setSizePolicy(sizePolicy)
        self.done_button.setObjectName("done_button")
        self.horizontalLayout_2.addWidget(self.done_button)
        self.verticalLayout.addWidget(self.frame)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.horizontalLayout.addWidget(self.dockWidget)
        self.sceneviewer_widget = SceneviewerWidget(SimpleVizWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneviewer_widget.sizePolicy().hasHeightForWidth())
        self.sceneviewer_widget.setSizePolicy(sizePolicy)
        self.sceneviewer_widget.setObjectName("sceneviewer_widget")
        self.horizontalLayout.addWidget(self.sceneviewer_widget)

        self.retranslateUi(SimpleVizWidget)
        self.toolBox.setCurrentIndex(5)
        self.toolBox.layout().setSpacing(2)
        QtCore.QMetaObject.connectSlotsByName(SimpleVizWidget)

    def retranslateUi(self, SimpleVizWidget):
        SimpleVizWidget.setWindowTitle(QtGui.QApplication.translate("SimpleVizWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("SimpleVizWidget", "SimpleViz Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.region_label.setText(QtGui.QApplication.translate("SimpleVizWidget", "Region:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.graphics), QtGui.QApplication.translate("SimpleVizWidget", "Graphics", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.view), QtGui.QApplication.translate("SimpleVizWidget", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.time_autorange_button.setText(QtGui.QApplication.translate("SimpleVizWidget", "Autorange time", None, QtGui.QApplication.UnicodeUTF8))
        self.time_minimum_label.setText(QtGui.QApplication.translate("SimpleVizWidget", "Minimum:", None, QtGui.QApplication.UnicodeUTF8))
        self.time_maximum_label.setText(QtGui.QApplication.translate("SimpleVizWidget", "Maximum:", None, QtGui.QApplication.UnicodeUTF8))
        self.time_label.setText(QtGui.QApplication.translate("SimpleVizWidget", "Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.time), QtGui.QApplication.translate("SimpleVizWidget", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.tessellation_groupbox.setTitle(QtGui.QApplication.translate("SimpleVizWidget", "Tessellation divisions:", None, QtGui.QApplication.UnicodeUTF8))
        self.tessellation_minimum_divisions_label.setText(QtGui.QApplication.translate("SimpleVizWidget", "Minimum:", None, QtGui.QApplication.UnicodeUTF8))
        self.tessellation_refinement_factors_label.setText(QtGui.QApplication.translate("SimpleVizWidget", "Refinement:", None, QtGui.QApplication.UnicodeUTF8))
        self.tessellation_circle_divisions_label.setText(QtGui.QApplication.translate("SimpleVizWidget", "Circle:", None, QtGui.QApplication.UnicodeUTF8))
        self.perturb_lines_checkbox.setText(QtGui.QApplication.translate("SimpleVizWidget", "Perturb lines", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.rendering), QtGui.QApplication.translate("SimpleVizWidget", "Rendering", None, QtGui.QApplication.UnicodeUTF8))
        self.spectrum_autorange_button.setText(QtGui.QApplication.translate("SimpleVizWidget", "Autorange spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.spectrum_minimum_label.setText(QtGui.QApplication.translate("SimpleVizWidget", "Minimum:", None, QtGui.QApplication.UnicodeUTF8))
        self.spectrum_maximum_label.setText(QtGui.QApplication.translate("SimpleVizWidget", "Maximum:", None, QtGui.QApplication.UnicodeUTF8))
        self.spectrum_add_colour_bar_button.setText(QtGui.QApplication.translate("SimpleVizWidget", "Add colour bar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.data_colouring), QtGui.QApplication.translate("SimpleVizWidget", "Data Colouring", None, QtGui.QApplication.UnicodeUTF8))
        self.save_image_button.setText(QtGui.QApplication.translate("SimpleVizWidget", "Save image...", None, QtGui.QApplication.UnicodeUTF8))
        self.save_webgl_button.setText(QtGui.QApplication.translate("SimpleVizWidget", "Save WebGL...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.output), QtGui.QApplication.translate("SimpleVizWidget", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.view_all_button.setText(QtGui.QApplication.translate("SimpleVizWidget", "View All", None, QtGui.QApplication.UnicodeUTF8))
        self.done_button.setText(QtGui.QApplication.translate("SimpleVizWidget", "Done", None, QtGui.QApplication.UnicodeUTF8))

from opencmiss.zincwidgets.sceneviewerwidget import SceneviewerWidget
from opencmiss.zincwidgets.regionchooserwidget import RegionChooserWidget
from opencmiss.zincwidgets.sceneviewereditorwidget import SceneviewerEditorWidget
from opencmiss.zincwidgets.sceneeditorwidget import SceneEditorWidget
